# Generated by Django 6.0.4 on 2026-09-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150)),
                ('project_type', models.CharField(blank=True, choices=[('web', 'Développement Web'), ('mobile', 'Application Mobile'), ('saas', 'Plateforme SaaS'), ('ecommerce', 'E-commerce'), ('integration', 'Intégration & API'), ('other', 'Autre')], max_length=50)),
                ('budget', models.CharField(blank=True, choices=[('<5k', 'Moins de 5 000 MAD'), ('5k-15k', '5 000 MAD - 15 000 MAD'), ('15k-50k', '15 000 MAD - 50 000 MAD'), ('50k+', 'Plus de 50 000 MAD'), ('discuss', 'À discuter')], max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
