# Generated by Django 6.0.8 on 2026-09-08 20:31

import apps.contact.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='marketing_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='marketing_consent_version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='marketing_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='privacy_notice_acknowledged_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='privacy_notice_version',
            field=models.CharField(default=apps.contact.models.current_privacy_notice_version, max_length=50),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='processing_purpose',
            field=models.CharField(default='contact_inquiry', editable=False, max_length=50),
        ),
    ]
