# Generated by Django 6.0.4 on 2026-09-08 18:53

import uuid
from django.db import migrations, models


def populate_access_tokens(apps, schema_editor):
    DevisRequest = apps.get_model("devis", "DevisRequest")
    for devis_request in DevisRequest.objects.filter(access_token__isnull=True):
        token = uuid.uuid4()
        while DevisRequest.objects.filter(access_token=token).exists():
            token = uuid.uuid4()
        devis_request.access_token = token
        devis_request.save(update_fields=["access_token"])


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devisrequest',
            name='access_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
        migrations.RunPython(populate_access_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='devisrequest',
            name='access_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
