# Generated by Codex on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="structured_state",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
