"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import dotenv_values, load_dotenv
import os
import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from core.utils.public_input_validation import PUBLIC_JSON_BODY_LIMIT_BYTES

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ENV_FILE = BASE_DIR / ".env"
LOAD_DOTENV = os.getenv("DJANGO_LOAD_DOTENV", "true").strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
LOCAL_ENV = dotenv_values(ENV_FILE) if LOAD_DOTENV else {}
if LOAD_DOTENV:
    load_dotenv(ENV_FILE)


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_int(name, default=0):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    try:
        return int(value.strip())
    except ValueError:
        raise ImproperlyConfigured(f"{name} must be an integer.")


def env_list(name, default=None):
    value = os.getenv(name)
    if not value:
        return default or []
    return [item.strip() for item in value.split(",") if item.strip()]


def env_str(name, default=""):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip()


def origins_from_hosts(hosts):
    origins = []
    for host in hosts:
        if host in {"*", "localhost", "127.0.0.1", "[::1]"}:
            continue
        if host.startswith("."):
            continue
        origins.append(f"https://{host}")
    return origins


def require_production_setting(condition, message):
    if not condition:
        raise ImproperlyConfigured(message)


DEFAULT_SECRET_KEY = "l;skndflknsdFO;SDFLSKFNBSLAKFSL,DJF"
PLACEHOLDER_SECRET_KEYS = {DEFAULT_SECRET_KEY, "change-me", "changeme"}
DEFAULT_ALLOWED_HOSTS = ["localhost", "127.0.0.1"]
DEFAULT_CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]
DEFAULT_PRODUCTION_CORS_ALLOWED_ORIGINS = [
    "https://smartdex.ma",
    "https://www.smartdex.ma",
]
CHROMA_DIR = os.getenv("CHROMA_DIR", str(BASE_DIR / "chroma_db"))
OPENAI_API_KEY = env_str("OPENAI_API_KEY")
SMARTDEX_PRIVACY_NOTICE_VERSION = env_str(
    "SMARTDEX_PRIVACY_NOTICE_VERSION",
    default="2026-09-08",
)
SMARTDEX_CONTACT_RETENTION_DAYS = env_int(
    "SMARTDEX_CONTACT_RETENTION_DAYS",
    default=365,
)
SMARTDEX_ABANDONED_DEVIS_RETENTION_DAYS = env_int(
    "SMARTDEX_ABANDONED_DEVIS_RETENTION_DAYS",
    default=365,
)
SMARTDEX_COMPLETED_DEVIS_RETENTION_DAYS = env_int(
    "SMARTDEX_COMPLETED_DEVIS_RETENTION_DAYS",
    default=2555,
)
SMARTDEX_CHATBOT_RETENTION_DAYS = env_int(
    "SMARTDEX_CHATBOT_RETENTION_DAYS",
    default=60,
)
SMARTDEX_TEMP_PDF_RETENTION_HOURS = env_int(
    "SMARTDEX_TEMP_PDF_RETENTION_HOURS",
    default=24,
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=env_bool("DEBUG", default=True))
IS_PRODUCTION = not DEBUG
DEPLOYMENT_ENVIRONMENT = env_str("DJANGO_ENV") or env_str("RAILWAY_ENVIRONMENT")
IS_RAILWAY_DEPLOYMENT = any(
    env_str(name)
    for name in ("RAILWAY_ENVIRONMENT", "RAILWAY_PROJECT_ID", "RAILWAY_SERVICE_ID")
)
if DEBUG and (
    IS_RAILWAY_DEPLOYMENT or DEPLOYMENT_ENVIRONMENT.lower() in {"production", "prod"}
):
    raise ImproperlyConfigured(
        "DJANGO_DEBUG must be false for Railway or production deployments."
    )

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_str("DJANGO_SECRET_KEY") or env_str("SECRET_KEY")
if not SECRET_KEY and DEBUG:
    SECRET_KEY = DEFAULT_SECRET_KEY

if IS_PRODUCTION:
    require_production_setting(
        SECRET_KEY and SECRET_KEY not in PLACEHOLDER_SECRET_KEYS,
        "DJANGO_SECRET_KEY or SECRET_KEY must be set to a non-placeholder value when DEBUG is false.",
    )

ALLOWED_HOSTS = env_list("ALLOWED_HOSTS", default=DEFAULT_ALLOWED_HOSTS)
if IS_PRODUCTION:
    require_production_setting(
        ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS,
        "ALLOWED_HOSTS must list explicit production hostnames when DEBUG is false.",
    )

CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    default=(
        DEFAULT_PRODUCTION_CORS_ALLOWED_ORIGINS
        if IS_PRODUCTION
        else DEFAULT_CORS_ALLOWED_ORIGINS
    ),
)
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = env_bool("CORS_ALLOW_CREDENTIALS", default=False)

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-devis-access-token",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS",
    default=origins_from_hosts(ALLOWED_HOSTS) if IS_PRODUCTION else [],
)

DATA_UPLOAD_MAX_MEMORY_SIZE = PUBLIC_JSON_BODY_LIMIT_BYTES
FILE_UPLOAD_MAX_MEMORY_SIZE = 1 * 1024 * 1024


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',

    # Local apps
    'apps.chatbot',
    'apps.contact',
    'apps.devis',
    'apps.health',
]

REST_FRAMEWORK = {
    "URL_FORMAT_OVERRIDE": None,
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "contact": os.getenv("THROTTLE_RATE_CONTACT", "5/hour"),
        "devis_create": os.getenv("THROTTLE_RATE_DEVIS_CREATE", "10/hour"),
        "devis_generate": os.getenv("THROTTLE_RATE_DEVIS_GENERATE", "10/hour"),
        "chatbot": os.getenv("THROTTLE_RATE_CHATBOT", "30/hour"),
    },
    "NUM_PROXIES": env_int("DRF_NUM_PROXIES", 1),
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
    ],
    "EXCEPTION_HANDLER": "core.utils.exception_handlers.public_exception_handler",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    "core.middleware.RequestBodySizeLimitMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = (
    LOCAL_ENV.get("DATABASE_URL")
    if "DATABASE_URL" in LOCAL_ENV
    else os.getenv("DATABASE_URL")
)
if IS_PRODUCTION:
    require_production_setting(
        bool(DATABASE_URL),
        "DATABASE_URL must be set when DEBUG is false.",
    )

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            ssl_require=DATABASE_URL.startswith(("postgres://", "postgresql://")),
        )
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": os.getenv("DB_ENGINE", "django.db.backends.sqlite3"),
            "NAME": os.getenv("DB_NAME", str(BASE_DIR / "db.sqlite3")),
            "USER": os.getenv("DB_USER", ""),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", ""),
            "PORT": os.getenv("DB_PORT", ""),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

USE_X_FORWARDED_PROTO = env_bool("USE_X_FORWARDED_PROTO", default=IS_PRODUCTION)
if USE_X_FORWARDED_PROTO:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=IS_PRODUCTION)
SECURE_HSTS_SECONDS = env_int("SECURE_HSTS_SECONDS", default=3600 if IS_PRODUCTION else 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS",
    default=False,
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=False)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
SECURE_CROSS_ORIGIN_OPENER_POLICY = "same-origin"

SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = env_str("SESSION_COOKIE_SAMESITE", default="Lax")
CSRF_COOKIE_SAMESITE = env_str("CSRF_COOKIE_SAMESITE", default="Lax")
X_FRAME_OPTIONS = "DENY"
