QUOTE_CATALOG = {
    "website_frontend": {
        "label": "Website / Frontend",
        "description": "Public-facing interface for clients or visitors.",
        "category": "core",
        "required_by": ["website", "webapp", "saas", "booking_system", "ecommerce"],
        "price_range": (8000, 20000),
        "optional": False,
        "recurring": False,
    },
    "admin_dashboard": {
        "label": "Admin Dashboard",
        "description": "Internal interface for managing content, users, bookings, and operations.",
        "category": "core",
        "required_by": ["webapp", "saas", "booking_system", "crm", "erp"],
        "price_range": (8000, 18000),
        "optional": False,
        "recurring": False,
    },
    "authentication": {
        "label": "User Authentication",
        "description": "Login, signup, and account access system.",
        "category": "core",
        "required_by": [],
        "price_range": (5000, 12000),
        "optional": False,
        "recurring": False,
    },
    "booking": {
        "label": "Booking System",
        "description": "Appointment and reservation management for clients.",
        "category": "core",
        "required_by": ["booking_system"],
        "price_range": (7000, 15000),
        "optional": False,
        "recurring": False,
    },
    "payments": {
        "label": "Online Payments",
        "description": "Payment flow and checkout integration.",
        "category": "integration",
        "required_by": ["ecommerce"],
        "price_range": (6000, 14000),
        "optional": True,
        "recurring": False,
    },
    "notifications": {
        "label": "Notifications System",
        "description": "Email, SMS, or WhatsApp reminders and alerts.",
        "category": "integration",
        "required_by": [],
        "price_range": (4000, 10000),
        "optional": True,
        "recurring": False,
    },
    "whatsapp": {
        "label": "WhatsApp Integration",
        "description": "Automated WhatsApp reminders and notifications.",
        "category": "integration",
        "required_by": [],
        "price_range": (5000, 12000),
        "optional": True,
        "recurring": False,
    },
    "analytics": {
        "label": "Analytics Dashboard",
        "description": "KPIs, reporting, and performance tracking.",
        "category": "optional",
        "required_by": [],
        "price_range": (6000, 15000),
        "optional": True,
        "recurring": False,
    },
    "chatbot": {
        "label": "AI Chatbot",
        "description": "AI assistant for client support or internal help.",
        "category": "optional",
        "required_by": [],
        "price_range": (10000, 25000),
        "optional": True,
        "recurring": False,
    },
    "deployment": {
        "label": "Deployment",
        "description": "Production deployment, server setup, and go-live configuration.",
        "category": "delivery",
        "required_by": ["website", "webapp", "saas", "booking_system", "ecommerce", "ai_system"],
        "price_range": (3000, 7000),
        "optional": False,
        "recurring": False,
    },
    "maintenance": {
        "label": "Monthly Maintenance",
        "description": "Bug fixes, small updates, monitoring, and technical support.",
        "category": "recurring",
        "required_by": [],
        "price_range": (500, 3000),
        "optional": True,
        "recurring": True,
    },
    "hosting": {
        "label": "Hosting / Infrastructure",
        "description": "Server hosting and infrastructure costs.",
        "category": "recurring",
        "required_by": [],
        "price_range": (300, 2000),
        "optional": True,
        "recurring": True,
    },
}